# Generated by Django 5.1.6 on 2025-03-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chattable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("senderid", models.TextField(max_length=5)),
                ("reciverid", models.TextField(max_length=5)),
                ("message", models.TextField(max_length=30)),
                ("diff", models.TextField(max_length=1)),
            ],
        ),
    ]
