# Generated by Django 5.1.6 on 2025-03-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_comminityjoin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Communitychatbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.IntegerField()),
                ("comminityid", models.IntegerField()),
                ("message", models.TextField(max_length=30)),
                ("a_status", models.IntegerField()),
            ],
        ),
    ]
