# Generated by Django 5.1.6 on 2025-02-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pcod_finder", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PCOSPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle_length", models.FloatField()),
                ("FSH", models.FloatField()),
                ("LH", models.FloatField()),
                ("FSH_LH", models.FloatField()),
                ("waist_hip_ratio", models.FloatField()),
                ("TSH", models.FloatField()),
                ("AMH", models.FloatField()),
                ("Vit_D3", models.FloatField()),
                ("PRG", models.FloatField()),
                ("RBS", models.FloatField()),
                ("weight_gain", models.IntegerField()),
                ("hair_growth", models.IntegerField()),
                ("skin_darkening", models.IntegerField()),
                ("hair_loss", models.IntegerField()),
                ("pimples", models.IntegerField()),
                ("follicle_L", models.IntegerField()),
                ("follicle_R", models.IntegerField()),
                ("avg_f_size_L", models.FloatField()),
                ("avg_f_size_R", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
