# Generated by Django 5.1.6 on 2025-03-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pcod_finder", "0003_pcosprediction_prediction_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertable",
            name="usertype",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
