# Generated by Django 5.1.6 on 2025-03-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pcod_finder", "0004_usertable_usertype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expert_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.CharField(max_length=30)),
                ("Specialization", models.CharField(max_length=30)),
                ("Experience", models.CharField(max_length=30)),
                ("Medical_License", models.CharField(max_length=30)),
                ("Educational_Qualifications", models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name="pcosprediction",
            name="userid",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
