# Generated by Django 5.1.6 on 2025-03-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expert", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="status",
            field=models.TextField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
