# Generated by Django 5.1.6 on 2025-03-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expert", "0002_community_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="date_c",
            field=models.DateField(auto_now=True),
        ),
    ]
